import Foundation

/// The word-to-glyph table at `assets/keyboard/emoji/suggestions.tsv`, and
/// nothing else.
///
/// Generated by `tools/generate-emoji-catalog.py` from Unicode names, CLDR
/// spoken names, and the curated overrides in
/// `tools/emoji-suggestion-overrides.tsv`. It is deliberately *not* the catalog
/// keyword set: those keywords answer a deliberate search in the emoji panel,
/// and matched against prose they answer "the" with 🤣 and "is" with the flag
/// of Iceland.
///
/// This used to live inside the keyboard extension's ``EmojiSuggestions``.
/// It is here because two features now read it and they are in different
/// targets: the typing strip in `VocaPhoneKeyboard`, and ``SpokenEmoji`` in the
/// transcript funnel, which the app target runs too. Only the table moved —
/// the strip's fuzzy matching stayed behind, because a spoken trigger must
/// never be fuzzy.
///
/// Keys are lower-cased with the spaces removed: "thumbs up" is `thumbsup`,
/// "loudly crying" is `loudlycrying`. That is also the join rule ``SpokenEmoji``
/// uses to look up a multi-word descriptor.
enum EmojiTable {
    /// The shortest key worth matching. Two letters are mostly initials,
    /// particles and typos.
    static let minimumLength = 2

    /// Word → glyph, loaded once.
    static let triggers: [String: String] = load()

    /// The longest key in the table, in characters.
    ///
    /// ``SpokenEmoji`` walks backwards from the trigger word accumulating a
    /// candidate key and stops when it passes this, which is a bound the table
    /// itself supplies rather than a guessed word count. A key cannot record
    /// how many words it was built from — the spaces are gone — so the length
    /// is the only honest limit available, and it is the tighter one anyway.
    /// The widest entry is currently `rollingonthefloorlaughing`, at five
    /// words — which is exactly why this is read off the table rather than
    /// written down: adding that phrase moved the bound on its own.
    static let widestKeyLength: Int = triggers.keys.reduce(0) { max($0, $1.count) }

    /// Parses the table now, so the first keystroke or transcript does not.
    ///
    /// Both stored properties above are lazy `static let`s, so somebody has to
    /// pay for the parse and for the pass that measures the widest key. This is
    /// the one place that says which, because touching only ``triggers`` leaves
    /// ``widestKeyLength`` still to be computed on whoever gets there first.
    ///
    /// Callers decide the thread; both entry points warm it off the main one.
    static func warmUp() {
        _ = triggers
        _ = widestKeyLength
    }

    static func glyph(forKey key: String) -> String? {
        guard key.count >= minimumLength else { return nil }
        return triggers[key]
    }

    static func parse(_ text: String) -> [String: String] {
        var table: [String: String] = [:]
        table.reserveCapacity(4_000)
        for line in text.split(whereSeparator: \.isNewline) {
            if line.isEmpty || line.first == "#" { continue }
            let parts = line.split(separator: "\t", maxSplits: 1, omittingEmptySubsequences: false)
            guard parts.count == 2 else { continue }
            let word = parts[0].lowercased()
            let glyph = String(parts[1])
            guard !word.isEmpty, !glyph.isEmpty, table[word] == nil else { continue }
            table[word] = glyph
        }
        return table
    }

    private static func load() -> [String: String] {
        for url in candidateURLs() {
            if let text = try? String(contentsOf: url, encoding: .utf8) {
                let parsed = parse(text)
                if !parsed.isEmpty { return parsed }
            }
        }
        return [:]
    }

    private static func candidateURLs() -> [URL] {
        var urls: [URL] = []
        let bundles = [Bundle(for: EmojiTableAnchor.self), .main]
        for bundle in bundles {
            if let url = bundle.url(forResource: "suggestions", withExtension: "tsv") {
                urls.append(url)
            }
            if let url = bundle.url(forResource: "emoji/suggestions", withExtension: "tsv") {
                urls.append(url)
            }
        }
        // Unit tests compile this file into a bundle that does not embed the
        // shared keyboard assets. The repository copy is the same file the two
        // keyboards ship, and `#filePath` is how `EmojiCatalogTests` finds it.
        // `VocaPhoneShared` sits at the same depth as the old home in
        // `VocaPhoneKeyboard`, so the walk up is unchanged: three components
        // to the repository root.
        urls.append(
            URL(fileURLWithPath: #filePath)
                .deletingLastPathComponent()
                .deletingLastPathComponent()
                .deletingLastPathComponent()
                .appendingPathComponent("assets/keyboard/emoji/suggestions.tsv")
        )
        return urls
    }
}

/// `Bundle(for:)` needs a class. The enum above is not one.
private final class EmojiTableAnchor: NSObject {}
