package com.vocahq.vocaphone.core

import android.content.res.AssetManager
import java.io.File

/**
 * The word-to-glyph table at `assets/keyboard/emoji/suggestions.tsv`, and
 * nothing else.
 *
 * Generated by `tools/generate-emoji-catalog.py` from Unicode names, CLDR
 * spoken names, and the curated overrides in
 * `tools/emoji-suggestion-overrides.tsv`. It is deliberately *not* the catalog
 * keyword set: those keywords answer a deliberate search in the emoji panel,
 * and matched against prose they answer "the" with 🤣 and "dog" with 💩.
 *
 * This used to live inside the keyboard's `EmojiSuggestions`. It is here
 * because two features now read it and they sit in different packages: the
 * typing strip in `ime`, and [SpokenEmoji] in the transcript funnel, which
 * `core` owns and `ime` may not be depended on from. Only the table moved —
 * the strip's fuzzy matching stayed behind, because a spoken trigger must
 * never be fuzzy.
 *
 * Keys are lower-cased with the spaces removed: "thumbs up" is `thumbsup`,
 * "loudly crying" is `loudlycrying`. That is also the join rule [SpokenEmoji]
 * uses to look up a multi-word descriptor.
 */
object EmojiTable {
    /**
     * The shortest key worth matching. Two letters are mostly initials,
     * particles and typos.
     */
    const val MINIMUM_LENGTH = 2

    /**
     * Word → glyph. Production binds [AssetManager] from
     * `VocaPhoneApplication` and warms the table off the main thread; the
     * first read still loads synchronously from those assets if warm has not
     * finished, so a transcript that finishes during startup never sees a
     * permanently empty table. JVM tests that never bind assets pick up the
     * same file by walking up to the repository root on first read, so the
     * object's init does no I/O.
     */
    @Volatile
    private var table: Map<String, String> = emptyMap()

    @Volatile
    private var widest: Int = 0

    /**
     * Whether the repository fallback has already been tried. Without it a
     * process that has no table — a device, where the repository is not on
     * disk — walks the filesystem to the root on every single lookup.
     */
    @Volatile
    private var discovered = false

    /**
     * Assets held so the first [triggers] read can finish the load if the
     * async warm from `VocaPhoneApplication` is still in flight.
     */
    @Volatile
    private var boundAssets: AssetManager? = null

    val triggers: Map<String, String>
        get() {
            val current = table
            if (current.isNotEmpty()) return current
            synchronized(this) {
                if (table.isNotEmpty()) return table
                val assets = boundAssets
                if (assets != null) {
                    runCatching { loadFromAssets(assets) }
                    return table
                }
                if (discovered) return table
                discovered = true
                val found = discoverFromRepository()
                if (found.isNotEmpty()) install(found)
                return table
            }
        }

    /**
     * The longest key in the table, in characters.
     *
     * [SpokenEmoji] walks backwards from the trigger word accumulating a
     * candidate key and stops when it passes this, which is a bound the table
     * itself supplies rather than a guessed word count. A key cannot record how
     * many words it was built from — the spaces are gone — so the length is the
     * only honest limit available, and it is the tighter one anyway. The widest
     * entry is currently `rollingonthefloorlaughing`, at five words — which is
     * exactly why this is read off the table rather than written down: adding
     * that phrase moved the bound on its own.
     */
    val widestKeyLength: Int
        get() {
            triggers
            return widest
        }

    fun glyphForKey(key: String): String? {
        if (key.length < MINIMUM_LENGTH) return null
        return triggers[key]
    }

    fun parse(text: String): Map<String, String> {
        val parsed = LinkedHashMap<String, String>()
        for (line in text.lineSequence()) {
            if (line.isEmpty() || line.startsWith("#")) continue
            val tab = line.indexOf('\t')
            if (tab <= 0) continue
            val word = line.substring(0, tab).lowercase()
            val glyph = line.substring(tab + 1)
            if (word.isEmpty() || glyph.isEmpty()) continue
            parsed.putIfAbsent(word, glyph)
        }
        return parsed
    }

    fun install(parsed: Map<String, String>) {
        table = parsed
        widest = parsed.keys.maxOfOrNull { it.length } ?: 0
    }

    /**
     * Remember the process [AssetManager] before the async warm starts, so a
     * first read that races the warm can still open the shipped file.
     */
    fun bind(assets: AssetManager) {
        boundAssets = assets
    }

    /**
     * The one place the shipped file is read.
     *
     * Called from `VocaPhoneApplication.onCreate`, which runs for every process
     * start, because both readers need it and only one of them is the keyboard:
     * the typing strip runs in the input method service, and [SpokenEmoji] runs
     * wherever a transcript is finished, the app's own recordings included.
     * Loading it from the service alone left spoken emoji silently doing
     * nothing for anyone who dictated from the app.
     *
     * Idempotent under [synchronized]: the async warm and a synchronous first
     * use of [triggers] can both arrive here; only the first parse installs.
     */
    fun load(assets: AssetManager) {
        bind(assets)
        synchronized(this) {
            if (table.isNotEmpty()) return
            loadFromAssets(assets)
        }
    }

    private fun loadFromAssets(assets: AssetManager) {
        install(
            assets.open("emoji/suggestions.tsv").bufferedReader().use { reader ->
                parse(reader.readText())
            }
        )
    }

    private fun discoverFromRepository(): Map<String, String> {
        val file = generateSequence(File("").absoluteFile) { it.parentFile }
            .map { File(it, "assets/keyboard/emoji/suggestions.tsv") }
            .firstOrNull(File::isFile)
            ?: return emptyMap()
        return parse(file.readText())
    }
}
